--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.505.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 4/15/2021 6:19:19 PM
-- Server version: 8.0.20
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP DATABASE IF EXISTS pc_build;

CREATE DATABASE IF NOT EXISTS pc_build
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

--
-- Set default database
--
USE pc_build;

--
-- Create table `category`
--
CREATE TABLE IF NOT EXISTS category (
  category_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  category_name VARCHAR(50) NOT NULL DEFAULT '',
  PRIMARY KEY (category_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 100126,
AVG_ROW_LENGTH = 655,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `product`
--
CREATE TABLE IF NOT EXISTS product (
  product_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  category_id MEDIUMINT UNSIGNED NOT NULL,
  product_name VARCHAR(100) DEFAULT NULL,
  product_price DOUBLE UNSIGNED DEFAULT NULL,
  PRIMARY KEY (product_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 144474,
AVG_ROW_LENGTH = 68,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE product 
  ADD CONSTRAINT FK_product_category_id FOREIGN KEY (category_id)
    REFERENCES category(category_id);

--
-- Create table `wireless_network_card`
--
CREATE TABLE IF NOT EXISTS wireless_network_card (
  wireless_network_card_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  protocol VARCHAR(50) DEFAULT NULL,
  interface VARCHAR(50) DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (wireless_network_card_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 395404,
AVG_ROW_LENGTH = 54,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `wireless_network_card`
--
ALTER TABLE wireless_network_card 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE wireless_network_card 
  ADD CONSTRAINT FK_wireless_network_card_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `wired_network_card`
--
CREATE TABLE IF NOT EXISTS wired_network_card (
  wired_network_card_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  interface VARCHAR(50) DEFAULT NULL,
  ports VARCHAR(50) DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (wired_network_card_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 390222,
AVG_ROW_LENGTH = 135,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `wired_network_card`
--
ALTER TABLE wired_network_card 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE wired_network_card 
  ADD CONSTRAINT FK_wired_network_card_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `video_card`
--
CREATE TABLE IF NOT EXISTS video_card (
  video_card_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  chipset VARCHAR(50) DEFAULT NULL,
  memory VARCHAR(50) DEFAULT NULL,
  core_clock VARCHAR(50) DEFAULT NULL,
  boost_clock VARCHAR(50) DEFAULT NULL,
  interface VARCHAR(50) DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  tdp_wattage INT DEFAULT NULL,
  PRIMARY KEY (video_card_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 384276,
AVG_ROW_LENGTH = 95,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `video_card`
--
ALTER TABLE video_card 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE video_card 
  ADD CONSTRAINT FK_video_card_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `ups`
--
CREATE TABLE IF NOT EXISTS ups (
  ups_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  capacity_w SMALLINT UNSIGNED DEFAULT NULL,
  capacity_va SMALLINT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (ups_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 375759,
AVG_ROW_LENGTH = 74,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `ups`
--
ALTER TABLE ups 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE ups 
  ADD CONSTRAINT FK_ups_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `thermal_paste`
--
CREATE TABLE IF NOT EXISTS thermal_paste (
  thermal_paste_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  amount VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (thermal_paste_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 370204,
AVG_ROW_LENGTH = 159,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `thermal_paste`
--
ALTER TABLE thermal_paste 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE thermal_paste 
  ADD CONSTRAINT FK_thermal_paste_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `speakers`
--
CREATE TABLE IF NOT EXISTS speakers (
  speakers_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  configuration ENUM('1.0','2.0','2.1','5.1') DEFAULT NULL,
  total_wattage VARCHAR(50) DEFAULT NULL,
  frequency_response VARCHAR(50) DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (speakers_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 365296,
AVG_ROW_LENGTH = 84,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `speakers`
--
ALTER TABLE speakers 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE speakers 
  ADD CONSTRAINT FK_speakers_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `sound_card`
--
CREATE TABLE IF NOT EXISTS sound_card (
  sound_card_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  channels ENUM('2.0','4.0','5.1','7.1') DEFAULT NULL,
  digital_audio ENUM('24-bit','16-bit','32-bit') DEFAULT NULL,
  snr VARCHAR(50) DEFAULT NULL,
  sample_rate VARCHAR(50) DEFAULT NULL,
  chipset VARCHAR(50) DEFAULT NULL,
  interface VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (sound_card_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 360172,
AVG_ROW_LENGTH = 230,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `sound_card`
--
ALTER TABLE sound_card 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE sound_card 
  ADD CONSTRAINT FK_sound_card_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `software`
--
CREATE TABLE IF NOT EXISTS software (
  software_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  software_type VARCHAR(50) DEFAULT NULL,
  media_type ENUM('Download','CD/DVD','Product Key Card') DEFAULT NULL,
  PRIMARY KEY (software_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 355244,
AVG_ROW_LENGTH = 114,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `software`
--
ALTER TABLE software 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE software 
  ADD CONSTRAINT FK_software_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `power_supply`
--
CREATE TABLE IF NOT EXISTS power_supply (
  power_supply_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  form_factor VARCHAR(50) DEFAULT NULL,
  efficiency_rating VARCHAR(50) DEFAULT NULL,
  total_wattage SMALLINT UNSIGNED DEFAULT NULL,
  modular ENUM('Full','No','Semi') DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  tdp INT DEFAULT NULL,
  PRIMARY KEY (power_supply_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 352128,
AVG_ROW_LENGTH = 64,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `power_supply`
--
ALTER TABLE power_supply 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE power_supply 
  ADD CONSTRAINT FK_power_supply_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `pc_case`
--
CREATE TABLE IF NOT EXISTS pc_case (
  case_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  case_type VARCHAR(50) DEFAULT NULL,
  form_factor VARCHAR(50) DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  power_supply VARCHAR(50) DEFAULT NULL,
  side_panel_window VARCHAR(50) DEFAULT NULL,
  external_bays TINYINT UNSIGNED DEFAULT NULL,
  internal_bays TINYINT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (case_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 258980,
AVG_ROW_LENGTH = 76,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `pc_case`
--
ALTER TABLE pc_case 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE pc_case 
  ADD CONSTRAINT FK_pc_case_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `os`
--
CREATE TABLE IF NOT EXISTS os (
  os_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  os_type ENUM('Windows','iOS','Android','Linux') DEFAULT NULL,
  mode ENUM('64-bit','32-bit','32/64-bit') DEFAULT NULL,
  max_memory VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (os_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 345157,
AVG_ROW_LENGTH = 292,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `os`
--
ALTER TABLE os 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE os 
  ADD CONSTRAINT FK_os_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `optical_drive`
--
CREATE TABLE IF NOT EXISTS optical_drive (
  optical_drive_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  bd TINYINT UNSIGNED DEFAULT NULL,
  dvd TINYINT UNSIGNED DEFAULT NULL,
  cd TINYINT DEFAULT NULL,
  bd_write VARCHAR(50) DEFAULT NULL,
  dvd_write VARCHAR(50) DEFAULT NULL,
  cd_write VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (optical_drive_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 340318,
AVG_ROW_LENGTH = 75,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `optical_drive`
--
ALTER TABLE optical_drive 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE optical_drive 
  ADD CONSTRAINT FK_optical_drive_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `mouse`
--
CREATE TABLE IF NOT EXISTS mouse (
  mouse_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  tracking_method ENUM('Optical','Laser','Touchpad','Trackball') DEFAULT NULL,
  connection_type ENUM('Bluetooth Wireless','Wired','Wireless') DEFAULT NULL,
  maximum_dpi SMALLINT DEFAULT NULL,
  hand_orientation ENUM('Right','Left','Both') DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (mouse_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 337049,
AVG_ROW_LENGTH = 58,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `mouse`
--
ALTER TABLE mouse 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE mouse 
  ADD CONSTRAINT FK_mouse_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `motherboard`
--
CREATE TABLE IF NOT EXISTS motherboard (
  motherboard_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  socket_type VARCHAR(50) DEFAULT NULL,
  form_factor VARCHAR(50) DEFAULT NULL,
  ram_gen VARCHAR(5) DEFAULT NULL,
  ram_slots TINYINT DEFAULT NULL,
  max_ram VARCHAR(50) DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (motherboard_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 333141,
AVG_ROW_LENGTH = 70,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `motherboard`
--
ALTER TABLE motherboard 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE motherboard 
  ADD CONSTRAINT FK_motherboard_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `monitor`
--
CREATE TABLE IF NOT EXISTS monitor (
  monitor_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  screen_size VARCHAR(50) DEFAULT NULL,
  resolution VARCHAR(50) DEFAULT NULL,
  refresh_rate VARCHAR(10) DEFAULT NULL,
  `response_time_(g2g)` VARCHAR(10) DEFAULT NULL,
  panel_type VARCHAR(10) DEFAULT NULL,
  aspect_ratio VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (monitor_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 327869,
AVG_ROW_LENGTH = 82,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `monitor`
--
ALTER TABLE monitor 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE monitor 
  ADD CONSTRAINT FK_monitor_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `memory`
--
CREATE TABLE IF NOT EXISTS memory (
  memory_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  ram_gen VARCHAR(5) DEFAULT NULL,
  speed SMALLINT UNSIGNED DEFAULT NULL,
  memory_type VARCHAR(50) DEFAULT NULL,
  modules VARCHAR(50) DEFAULT NULL,
  price_per_gb DOUBLE DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  cas_latency TINYINT DEFAULT NULL,
  PRIMARY KEY (memory_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 322252,
AVG_ROW_LENGTH = 225,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `memory`
--
ALTER TABLE memory 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE memory 
  ADD CONSTRAINT FK_memory_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `keyboard`
--
CREATE TABLE IF NOT EXISTS keyboard (
  keyboard_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  style ENUM('Ergonomic','Gaming','Mini','Slim','Standard') DEFAULT NULL,
  switch_type VARCHAR(50) DEFAULT NULL,
  backlit VARCHAR(50) DEFAULT NULL,
  tenkeyless ENUM('No','Yes') DEFAULT NULL,
  connection_type ENUM('Bluetooth Wireless','Wired','Wireless') DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (keyboard_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 312364,
AVG_ROW_LENGTH = 65,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `keyboard`
--
ALTER TABLE keyboard 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE keyboard 
  ADD CONSTRAINT FK_keyboard_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `internal_harddrive`
--
CREATE TABLE IF NOT EXISTS internal_harddrive (
  internal_harddrive_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  capacity VARCHAR(10) DEFAULT NULL,
  price_per_gb DOUBLE DEFAULT NULL,
  harddrive_type VARCHAR(50) DEFAULT NULL,
  cache VARCHAR(255) DEFAULT NULL,
  form_factor VARCHAR(50) DEFAULT NULL,
  interface VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (internal_harddrive_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 303889,
AVG_ROW_LENGTH = 77,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `internal_harddrive`
--
ALTER TABLE internal_harddrive 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE internal_harddrive 
  ADD CONSTRAINT FK_internal_harddrive_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `headphones`
--
CREATE TABLE IF NOT EXISTS headphones (
  headphones_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  headphones_type ENUM('Circumaural','Earbud','In Ear','Supra-aural') DEFAULT NULL,
  frequency_response VARCHAR(50) DEFAULT NULL,
  microphone ENUM('Yes','No') DEFAULT NULL,
  wireless ENUM('Yes','No') DEFAULT NULL,
  enclosure_type ENUM('Closed','Open','Semi-Open') DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (headphones_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 301564,
AVG_ROW_LENGTH = 71,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `headphones`
--
ALTER TABLE headphones 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE headphones 
  ADD CONSTRAINT FK_headphones_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `fan_controller`
--
CREATE TABLE IF NOT EXISTS fan_controller (
  fan_controller_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  channels TINYINT UNSIGNED DEFAULT NULL,
  channel_wattage VARCHAR(10) DEFAULT NULL,
  pwm_4_pin ENUM('Yes','No') DEFAULT NULL,
  form_factor VARCHAR(20) DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (fan_controller_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 290143,
AVG_ROW_LENGTH = 455,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `fan_controller`
--
ALTER TABLE fan_controller 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE fan_controller 
  ADD CONSTRAINT FK_fan_controller_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `external_harddrive`
--
CREATE TABLE IF NOT EXISTS external_harddrive (
  external_harddrive_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  hardrive_type ENUM('Portable','Desktop') DEFAULT NULL,
  interface VARCHAR(255) DEFAULT NULL,
  capacity VARCHAR(50) DEFAULT NULL,
  price_per_gb DOUBLE DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (external_harddrive_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 285420,
AVG_ROW_LENGTH = 154,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `external_harddrive`
--
ALTER TABLE external_harddrive 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE external_harddrive 
  ADD CONSTRAINT FK_external_harddrive_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `cpu_cooler`
--
CREATE TABLE IF NOT EXISTS cpu_cooler (
  cpu_cooler_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  socket_type VARCHAR(50) DEFAULT NULL,
  fan_rpm VARCHAR(50) DEFAULT NULL,
  noise_level VARCHAR(50) DEFAULT NULL,
  radiator_size VARCHAR(50) DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (cpu_cooler_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 281212,
AVG_ROW_LENGTH = 73,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `cpu_cooler`
--
ALTER TABLE cpu_cooler 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE cpu_cooler 
  ADD CONSTRAINT FK_cpu_cooler_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `cpu`
--
CREATE TABLE IF NOT EXISTS cpu (
  cpu_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  socket_type VARCHAR(50) DEFAULT NULL,
  core_count TINYINT UNSIGNED DEFAULT NULL,
  core_clock VARCHAR(10) DEFAULT NULL,
  boost_clock VARCHAR(10) DEFAULT NULL,
  mode ENUM('64-bit','32-bit','32/64-bit') DEFAULT '32/64-bit',
  integrated_graphics VARCHAR(50) DEFAULT NULL,
  smt ENUM('Yes','No') DEFAULT NULL,
  tdp_wattage INT DEFAULT NULL,
  PRIMARY KEY (cpu_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 276314,
AVG_ROW_LENGTH = 81,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `cpu`
--
ALTER TABLE cpu 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE cpu 
  ADD CONSTRAINT FK_cpu_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `case_fan`
--
CREATE TABLE IF NOT EXISTS case_fan (
  case_fan_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  mm_size TINYINT UNSIGNED DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  rpm VARCHAR(50) DEFAULT NULL,
  airflow VARCHAR(50) DEFAULT NULL,
  noise_level VARCHAR(50) DEFAULT NULL,
  pwm_4_pin ENUM('Yes','No') DEFAULT NULL,
  PRIMARY KEY (case_fan_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 271593,
AVG_ROW_LENGTH = 87,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `case_fan`
--
ALTER TABLE case_fan 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE case_fan 
  ADD CONSTRAINT FK_case_fan_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `case_accessory`
--
CREATE TABLE IF NOT EXISTS case_accessory (
  case_accesssory_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  acc_type ENUM('LED Controller','Card Reader') DEFAULT NULL,
  form_factor DOUBLE UNSIGNED DEFAULT NULL,
  PRIMARY KEY (case_accesssory_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 265109,
AVG_ROW_LENGTH = 2048,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `product_id` on table `case_accessory`
--
ALTER TABLE case_accessory 
  ADD UNIQUE INDEX product_id(product_id);

--
-- Create foreign key
--
ALTER TABLE case_accessory 
  ADD CONSTRAINT FK_case_accessory_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

--
-- Create table `user`
--
CREATE TABLE IF NOT EXISTS user (
  user_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 250101,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `product_rating`
--
CREATE TABLE IF NOT EXISTS product_rating (
  rating_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id MEDIUMINT UNSIGNED NOT NULL,
  procduct_id MEDIUMINT UNSIGNED NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  rating ENUM('1','2','3','4','5') DEFAULT NULL,
  comment TEXT DEFAULT NULL,
  created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_data TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (rating_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 805101,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE product_rating 
  ADD CONSTRAINT FK_product_rating_procduct_id FOREIGN KEY (procduct_id)
    REFERENCES product(product_id);

--
-- Create foreign key
--
ALTER TABLE product_rating 
  ADD CONSTRAINT FK_product_rating_user_id FOREIGN KEY (user_id)
    REFERENCES user(user_id);

--
-- Create table `build`
--
CREATE TABLE IF NOT EXISTS build (
  build_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id MEDIUMINT UNSIGNED NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  mode ENUM('64-bit','32-bit','32/64-bit') DEFAULT NULL,
  socket_type VARCHAR(50) DEFAULT NULL,
  form_factor VARCHAR(50) DEFAULT NULL,
  ram_gen VARCHAR(5) DEFAULT NULL,
  ram_slots TINYINT DEFAULT NULL,
  total_tdp SMALLINT UNSIGNED DEFAULT NULL,
  cpu_tdp SMALLINT UNSIGNED DEFAULT NULL,
  video_card_tdp SMALLINT UNSIGNED DEFAULT NULL,
  created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_data TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (build_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 450101,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE build 
  ADD CONSTRAINT FK_build_user_id FOREIGN KEY (user_id)
    REFERENCES user(user_id);

--
-- Create table `build_product`
--
CREATE TABLE IF NOT EXISTS build_product (
  build_product_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  build_id MEDIUMINT UNSIGNED NOT NULL,
  product_id MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (build_product_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 605101,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE build_product 
  ADD CONSTRAINT FK_build_product_build_id FOREIGN KEY (build_id)
    REFERENCES build(build_id);

--
-- Create foreign key
--
ALTER TABLE build_product 
  ADD CONSTRAINT FK_build_product_product_id FOREIGN KEY (product_id)
    REFERENCES product(product_id);

CREATE USER IF NOT EXISTS 'mysql.infoschema'@'localhost' IDENTIFIED WITH caching_sha2_password PASSWORD EXPIRE DEFAULT ACCOUNT LOCK;
GRANT SELECT ON *.* TO 'mysql.infoschema'@'localhost';



CREATE USER IF NOT EXISTS 'mysql.session'@'localhost' IDENTIFIED WITH caching_sha2_password PASSWORD EXPIRE DEFAULT ACCOUNT LOCK;
GRANT SHUTDOWN, SUPER, BACKUP_ADMIN, PERSIST_RO_VARIABLES_ADMIN, CLONE_ADMIN, CONNECTION_ADMIN, SESSION_VARIABLES_ADMIN, SYSTEM_USER, SYSTEM_VARIABLES_ADMIN ON *.* TO 'mysql.session'@'localhost';
GRANT SELECT ON  performance_schema.* TO 'mysql.session'@'localhost';



CREATE USER IF NOT EXISTS 'mysql.sys'@'localhost' IDENTIFIED WITH caching_sha2_password PASSWORD EXPIRE DEFAULT ACCOUNT LOCK;
GRANT TRIGGER ON  sys.* TO 'mysql.sys'@'localhost';



CREATE USER IF NOT EXISTS 'pc_admin'@'%' IDENTIFIED WITH mysql_native_password PASSWORD EXPIRE DEFAULT;
GRANT Usage ON *.* TO 'pc_admin'@'%' 
WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'pc_admin'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, EVENT, TRIGGER ON  pc_build.* TO 'pc_admin'@'%';



CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED WITH caching_sha2_password PASSWORD EXPIRE DEFAULT;
GRANT Usage ON *.* TO 'root'@'localhost' 
WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';
GRANT PROXY ON ''@'' TO 'root'@'localhost' WITH GRANT OPTION;



-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;