package com.pcbuilder.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Build generated by hbm2java
 */
public class Build  implements Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name="build_id")
	private int buildId;
	
	//bi-directional many-to-one association to Build
	@ManyToOne
	@JoinColumn(name="user_id")
     private User user;
	
	@Column(name="active")
     private boolean active;
	@Column(name="created_date")
     private Date createdDate;
	@Column(name="updated_data")
     private Date updatedData;

	//bi-directional many-to-one association to Build
	@ManyToOne
	@JoinColumn(name="build_product_id")
     private BuildProduct buildProduct;

    public Build() {
    }
   
    public Integer getBuildId() {
        return this.buildId;
    }
    
    public void setBuildId(Integer buildId) {
        this.buildId = buildId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getUpdatedData() {
        return this.updatedData;
    }
    
    public void setUpdatedData(Date updatedData) {
        this.updatedData = updatedData;
    }


	public BuildProduct getBuildProduct() {
		return buildProduct;
	}


	public void setBuildProduct(BuildProduct buildProduct) {
		this.buildProduct = buildProduct;
	}

}

